# Generated by Django 6.1.1 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome de urna')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nome completo')),
                ('category', models.CharField(choices=[('president', 'Presidente'), ('governor', 'Governador'), ('deputy_federal', 'Deputado Federal'), ('deputy_state', 'Deputado Estadual'), ('senator', 'Senador')], max_length=20, verbose_name='Cargo')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('party', models.CharField(max_length=10, verbose_name='Partido (sigla)')),
                ('party_name', models.CharField(blank=True, max_length=100, verbose_name='Partido (nome)')),
                ('number', models.IntegerField(unique=True, verbose_name='Número')),
                ('vice', models.CharField(blank=True, max_length=200, verbose_name='Vice')),
                ('vice_party', models.CharField(blank=True, max_length=10, verbose_name='Partido do vice')),
                ('coalition', models.CharField(blank=True, max_length=200, verbose_name='Coligação')),
                ('birth_date', models.CharField(blank=True, max_length=50, verbose_name='Nascimento')),
                ('birthplace', models.CharField(blank=True, max_length=200, verbose_name='Naturalidade')),
                ('profession', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('education', models.CharField(blank=True, max_length=200, verbose_name='Formação')),
                ('trajectory', models.TextField(blank=True, verbose_name='Trajetória')),
                ('status_tse', models.CharField(default='Validado', max_length=50, verbose_name='Status TSE')),
                ('photo', models.ImageField(blank=True, upload_to='candidates/', verbose_name='Foto')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['category', 'order', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='candidates__categor_5a85c4_idx'), models.Index(fields=['slug'], name='candidates__slug_345b9c_idx')],
            },
        ),
    ]
