# Generated by Django 6.1.1 on 2026-09-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='proposals',
            field=models.JSONField(blank=True, default=dict, verbose_name='Propostas'),
        ),
    ]
