# Generated by Django 6.1.1 on 2026-09-18 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Chave única')),
                ('label', models.CharField(max_length=200, verbose_name='Rótulo amigável')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('content_type', models.CharField(choices=[('text', 'Texto simples'), ('html', 'HTML rico'), ('list', 'Lista (uma linha por item)'), ('json', 'JSON estruturado')], default='text', max_length=10, verbose_name='Tipo')),
                ('help_text', models.TextField(blank=True, verbose_name='Ajuda para o editor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Bloco de Conteúdo',
                'verbose_name_plural': 'Blocos de Conteúdo',
                'ordering': ['key'],
            },
        ),
    ]
