# Generated by Django 6.1.1 on 2026-09-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(verbose_name='Frente')),
                ('back', models.TextField(verbose_name='Verso')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pergunta')),
                ('options', models.JSONField(help_text='[{"text": "Opção A", "correct": true}, {"text": "Opção B", "correct": false}]', verbose_name='Opções')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicação')),
                ('category', models.CharField(default='Geral', max_length=50, verbose_name='Categoria')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pergunta do Quiz',
                'verbose_name_plural': 'Perguntas do Quiz',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SenatorGameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título do Cenário')),
                ('scenario', models.TextField(verbose_name='Cenário/Contexto')),
                ('options', models.JSONField(help_text='[{"text": "Opção", "effects": {...}}]', verbose_name='Opções')),
                ('consequences', models.JSONField(blank=True, default=dict, verbose_name='Consequências')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Cenário - Você é o Senador',
                'verbose_name_plural': 'Cenários - Você é o Senador',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SimulatorScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('steps', models.JSONField(help_text='Estrutura JSON do simulador', verbose_name='Passos/Etapas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cenário do Simulador',
                'verbose_name_plural': 'Cenários do Simulador',
            },
        ),
    ]
